eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8080/eureka/,http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8081/eureka/
  instance:
    appname: ribbon-consumer
    hostname: localhost
  server:
    security:
      name: admin
      password: 123456
server:
  port: 8091
spring:
  application:
    name: ribbon-consumer
service-url:
  http: http://
  business-service: ${service-url.http}business-service
ribbon:
  #服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  #服务请求处理超时时间（毫秒）
  ReadTimeout: 3000
  #对超时请求启用重试机制
  OkToRetryOnAllOperations: true
  http:
    client:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000