eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8080/eureka/,http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8081/eureka/
  instance:
    appname: gateway
    hostname: localhost
    virtual-host-name: gateway
  server:
    security:
      name: admin
      password: 123456
server:
  port: 8070
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://www.ityouknow.com
          predicates:
            - Path=/spring-cloud

