eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8080/eureka/,http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8081/eureka/
  instance:
    appname: feign-consumer
    hostname: localhost
  server:
    security:
      name: admin
      password: 123456
server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 1024
spring:
  application:
    name: feign-consumer
logging:
  level:
    com.example.feignconsumer.business.*: debug
feign:
  hystrix:
    enabled: true
  compression:
    request:
      #\u5F00\u8BF7\u6C42\u538B\u7F29
      enabled: true
      #\u5A92\u4F53\u7C7B\u578B
      mimeTypes: text/xml,application/xml,application/json
      #\u6700\u5C0F\u7684\u8BF7\u6C42\u5927\u5C0F
      minRequestSize: 1024
    response:
      enabled: true #\u5F00\u542F\u54CD\u5E94\u7684\u538B\u7F29
  metrics:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000