eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8080/eureka/,http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8081/eureka/
  instance:
    appname: feign-consumer
    hostname: localhost
  server:
    security:
      name: admin
      password: 123456
server:
  port: 8090
spring:
  application:
    name: feign-consumer
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
logging:
  level:
    com.example.feignconsumer.business.*: debug
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true #开请求压缩
      mimeTypes: #媒体类型 text/xml,application/xml,application/json
      minRequestSize: 1024 #最小的请求大小
    response:
      enabled: true #开启响应的压缩
      useGzipDecoder: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
