eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
  instance:
    appname: business-service-b
    hostname: localhost
    virtual-host-name: business-service
server:
  port: 8086
spring:
  application:
    name: business-service