eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    appname: eureka-server
    hostname: localhost
server:
  port: 8080