eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8081/eureka/
  server:
    enableSelfPreservation: false
  instance:
    appname: eureka-server
    hostname: localhost
    healthCheckUrlPath: example/health
    statusPageUrlPath: example/info
    prefer-ip-address: true
server:
  port: 8080
spring:
  security:
    user:
      name: admin
      password: 123456