eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8080/eureka/,http://${eureka.server.security.name}:${eureka.server.security.password}@localhost:8081/eureka/
#    healthcheck:
#      enabled: true
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    virtual-host-name: ${spring.application.name}
  server:
    security:
      name: admin
      password: 123456
server:
  port: 8085
  compression:
    enabled: true
    min-response-size: 1024
  servlet:
    context-path: /example
spring:
  application:
    name: business-service