eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
  instance:
    appname: business-instance-a
    hostname: localhost
    virtual-host-name: business-instance
server:
  port: 8085
spring:
  application:
    name: business-instance